#  Copyright (c) 2024. Christopher Queen Consulting LLC (http://www.ChristopherQueenConsulting.com/)
import datetime as DT

import dateparser
import pytest

from cqc_cpcc.utilities.date import (
    calculate_census_date,
    is_checkdate_before_date,
    is_checkdate_after_date,
    is_date_in_range,
    weeks_between_dates,
)


# Generated by CodiumAI


class TestIsCheckdateBeforeDate:

    @pytest.mark.unit
    # check_date and before_date are both datetime objects and check_date is before before_date
    def test_checkdate_before_beforedate_datetime(self):
        check_date = DT.datetime(2023, 1, 1, 12, 0, 0)
        before_date = DT.datetime(2023, 1, 2, 12, 0, 0)
        assert is_checkdate_before_date(check_date, before_date) == True

    @pytest.mark.unit
    # check_date and before_date are the same datetime object
    def test_checkdate_equals_beforedate_datetime(self):
        check_date = DT.datetime(2023, 1, 1, 12, 0, 0)
        before_date = DT.datetime(2023, 1, 1, 12, 0, 0)
        assert is_checkdate_before_date(check_date, before_date) == False

    @pytest.mark.unit
    # check_date and before_date are the same date object
    def test_checkdate_equals_beforedate_date(self):
        check_date = DT.date(2023, 1, 1)
        before_date = DT.date(2023, 1, 1)
        assert is_checkdate_before_date(check_date, before_date) == False

    @pytest.mark.unit
    # check_date and before_date are both date objects and check_date is before before_date
    def test_checkdate_before_beforedate_date(self):
        check_date = DT.date(2023, 1, 1)
        before_date = DT.date(2023, 1, 2)
        assert is_checkdate_before_date(check_date, before_date) == True

    # NOTE: the four tests below previously shared two names with the ones above,
    # so Python replaced each definition and pytest only ever collected the last
    # of each pair -- the mixed date/datetime cases never ran. Names are now
    # unique and say which type combination each one covers.

    @pytest.mark.unit
    # datetime check_date, date before_date, check_date is the earlier day
    def test_checkdate_datetime_before_beforedate_date(self):
        check_date = DT.datetime(2023, 1, 1, 12, 0, 0)
        before_date = DT.date(2023, 1, 2)
        assert is_checkdate_before_date(check_date, before_date) == True

    @pytest.mark.unit
    # date check_date, datetime before_date, check_date is the earlier day
    def test_checkdate_date_before_beforedate_datetime(self):
        check_date = DT.date(2023, 1, 1)
        before_date = DT.datetime(2023, 1, 2, 12, 0, 0)
        assert is_checkdate_before_date(check_date, before_date) == True

    @pytest.mark.unit
    # datetime check_date, date before_date, same calendar day
    def test_checkdate_datetime_same_day_as_beforedate_date(self):
        """Same calendar day is not "before", in either type orientation.

        This test never ran before (its name was shadowed) and asserted True,
        which contradicts the documented contract: "if they fall on the same
        calendar day, they are considered equal (returns False)". The pair below
        pins the symmetry, which matters because is_checkdate_before_date decides
        whether a withdrawal dated on the course start day is tracked at all.
        """
        check_date = DT.datetime(2023, 1, 1, 12, 0, 0)
        before_date = DT.date(2023, 1, 1)
        assert is_checkdate_before_date(check_date, before_date) == False

    @pytest.mark.unit
    # date check_date, datetime before_date, same calendar day
    def test_checkdate_date_same_day_as_beforedate_datetime(self):
        check_date = DT.datetime(2023, 1, 1, 12, 0, 0).date()
        before_date = DT.datetime(2023, 1, 1, 12, 0, 0)
        assert is_checkdate_before_date(check_date, before_date) == False

    @pytest.mark.unit
    # both datetimes, check_date is after before_date
    def test_checkdate_datetime_after_beforedate_datetime(self):
        check_date = DT.datetime(2023, 1, 2, 12, 0, 0)
        before_date = DT.datetime(2023, 1, 1, 12, 0, 0)
        assert is_checkdate_before_date(check_date, before_date) == False

    @pytest.mark.unit
    # date check_date, datetime before_date, check_date is the later day
    def test_checkdate_date_after_beforedate_datetime(self):
        check_date = DT.date(2023, 1, 2)
        before_date = DT.datetime(2023, 1, 1, 12, 0, 0)
        assert is_checkdate_before_date(check_date, before_date) == False

    @pytest.mark.unit
    # check_date is a string that can be parsed to a date
    def test_checkdate_before_beforedate_string(self):
        check_date = dateparser.parse("2023-01-01")
        before_date = DT.datetime(2023, 1, 2, 12, 0, 0)
        assert is_checkdate_before_date(check_date, before_date) == True

    @pytest.mark.unit
    # before_date is a string that can be parsed to a date
    def test_before_date_string_parsable_to_date(self):
        check_date = DT.datetime(2023, 1, 1, 12, 0, 0)
        before_date = dateparser.parse("2023-01-02 12:00:00")
        assert is_checkdate_before_date(check_date, before_date) == True

    @pytest.mark.unit
    # check_date and before_date are both strings that can be parsed to dates
    def test_checkdate_before_beforedate_strings(self):
        check_date = "2023-01-01"
        before_date = "2023-01-02"
        assert is_checkdate_before_date(check_date, before_date) == True


class TestIsCheckdateAfterDate:

    @pytest.mark.unit
    # check_date and after_date are both datetime objects
    def test_both_datetime_objects(self):
        check_date = DT.datetime(2023, 10, 1, 12, 0, 0)
        after_date = DT.datetime(2023, 9, 30, 12, 0, 0)
        result = is_checkdate_after_date(check_date, after_date)
        assert result is True

    @pytest.mark.unit
    # check_date and after_date are the same datetime object
    def test_same_datetime_object(self):
        check_date = after_date = DT.datetime(2023, 10, 1, 12, 0, 0)
        result = is_checkdate_after_date(check_date, after_date)
        assert result is False

    @pytest.mark.unit
    # check_date and after_date are the same date object
    def test_same_date_object(self):
        check_date = after_date = DT.date(2023, 10, 1)
        result = is_checkdate_after_date(check_date, after_date)
        assert result is False

    @pytest.mark.unit
    # check_date and after_date are both date objects
    def test_both_date_objects(self):
        check_date = DT.date(2023, 10, 1)
        after_date = DT.date(2023, 9, 30)
        result = is_checkdate_after_date(check_date, after_date)
        assert result is True

    @pytest.mark.unit
    # check_date is a datetime object and after_date is a date object
    def test_checkdate_after_date(self):
        check_date = DT.datetime(2023, 10, 1, 12, 0, 0)
        after_date = DT.date(2023, 9, 30)
        result = is_checkdate_after_date(check_date, after_date)
        assert result is True

    @pytest.mark.unit
    # check_date is a date object and after_date is a datetime object
    def test_checkdate_date_after_datetime(self):
        check_date = DT.date(2023, 10, 1)
        after_date = DT.datetime(2023, 9, 30, 12, 0, 0)
        result = is_checkdate_after_date(check_date, after_date)
        assert result is True

    @pytest.mark.unit
    # check_date is the minimum possible datetime value
    def test_checkdate_min_datetime_value(self):
        check_date = DT.datetime.min
        after_date = DT.datetime(2023, 9, 30, 12, 0, 0)
        result = is_checkdate_after_date(check_date, after_date)
        assert result is False

    @pytest.mark.unit
    # after_date is the maximum possible datetime value
    def test_after_date_is_maximum_datetime_value(self):
        check_date = DT.datetime(2023, 10, 1, 12, 0, 0)
        after_date = DT.datetime.max
        result = is_checkdate_after_date(check_date, after_date)
        assert result is False


class TestIsDateInRange:

    @pytest.mark.unit
    # check_date is within the range of start_date and end_date
    def test_check_date_within_range(self):
        start_date = DT.datetime(2023, 1, 1)
        check_date = DT.datetime(2023, 1, 2)
        end_date = DT.datetime(2023, 1, 3)
        assert is_date_in_range(start_date, check_date, end_date) == True

    @pytest.mark.unit
    # start_date is after end_date
    def test_start_date_after_end_date(self):
        start_date = DT.datetime(2023, 1, 3)
        check_date = DT.datetime(2023, 1, 2)
        end_date = DT.datetime(2023, 1, 1)
        assert is_date_in_range(start_date, check_date, end_date) == False

    @pytest.mark.unit
    # check_date is before start_date
    def test_check_date_before_start_date(self):
        start_date = DT.datetime(2023, 1, 2)
        check_date = DT.datetime(2023, 1, 1)
        end_date = DT.datetime(2023, 1, 3)
        assert is_date_in_range(start_date, check_date, end_date) == False

    @pytest.mark.unit
    # check_date is exactly the same as start_date
    def test_check_date_same_as_start_date(self):
        start_date = DT.datetime(2023, 1, 1)
        check_date = DT.datetime(2023, 1, 1)
        end_date = DT.datetime(2023, 1, 3)
        assert is_date_in_range(start_date, check_date, end_date) == True

    @pytest.mark.unit
    # check_date is exactly the same as end_date
    def test_check_date_same_as_end_date(self):
        start_date = DT.datetime(2023, 1, 1)
        check_date = DT.datetime(2023, 1, 3)
        end_date = DT.datetime(2023, 1, 3)
        assert is_date_in_range(start_date, check_date, end_date) == True

    @pytest.mark.unit
    # start_date, check_date, and end_date are all DT.datetime objects
    def test_is_date_in_range_with_datetime_objects(self):
        start_date = DT.datetime(2023, 1, 1)
        check_date = DT.datetime(2023, 1, 2)
        end_date = DT.datetime(2023, 1, 3)
        assert is_date_in_range(start_date, check_date, end_date) == True

    @pytest.mark.unit
    # start_date, check_date, and end_date are all DT.date objects
    def test_is_date_in_range_with_dates_only(self):
        start_date = DT.date(2023, 1, 1)
        check_date = DT.date(2023, 1, 2)
        end_date = DT.date(2023, 1, 3)
        assert is_date_in_range(start_date, check_date, end_date) == True

    @pytest.mark.unit
    # check_date is after end_date
    def test_check_date_after_end_date(self):
        start_date = DT.datetime(2023, 1, 1)
        check_date = DT.datetime(2023, 1, 4)
        end_date = DT.datetime(2023, 1, 3)
        assert is_date_in_range(start_date, check_date, end_date) == False

    @pytest.mark.unit
    # start_date, check_date, and end_date are a mix of DT.date and DT.datetime objects
    def test_is_date_in_range_mixed_types(self):
        start_date = DT.date(2023, 1, 1)
        check_date = DT.datetime(2023, 1, 2)
        end_date = DT.date(2023, 1, 3)
        assert is_date_in_range(start_date, check_date, end_date) == True

    @pytest.mark.unit
    # start_date, check_date, and end_date are the same date
    def test_same_date(self):
        same_date = DT.datetime(2023, 1, 1)
        assert is_date_in_range(same_date, same_date, same_date) == True

    @pytest.mark.unit
    # check_date is at the exact boundary of start_date or end_date
    def test_check_date_at_boundary(self):
        start_date = DT.datetime(2023, 1, 1)
        check_date = DT.datetime(2023, 1, 2)
        end_date = DT.datetime(2023, 1, 2)
        assert is_date_in_range(start_date, check_date, end_date) == True

    @pytest.mark.unit
    # start_date and end_date are the same, and check_date is different
    def test_start_end_same_check_different(self):
        start_date = DT.datetime(2023, 1, 1)
        check_date = DT.datetime(2023, 1, 2)
        end_date = DT.datetime(2023, 1, 1)
        assert is_date_in_range(start_date, check_date, end_date) == False

    @pytest.mark.unit
    # check_date is exactly at the transition between two dates (e.g., midnight)
    def test_check_date_at_transition(self):
        start_date = DT.datetime(2023, 1, 1, 23, 59, 59)
        check_date = DT.datetime(2023, 1, 2, 0, 0, 0)
        end_date = DT.datetime(2023, 1, 3, 0, 0, 1)
        assert is_date_in_range(start_date, check_date, end_date) == True


class TestTimezoneAwarenessMixing:

    @pytest.mark.unit
    def test_before_date_timezone_aware_check_date_naive(self):
        check_date = DT.datetime(2023, 5, 1, 12, 0, 0)
        before_date = DT.datetime(2023, 5, 2, 12, 0, 0, tzinfo=DT.timezone.utc)
        assert is_checkdate_before_date(check_date, before_date) is True

    @pytest.mark.unit
    def test_after_date_timezone_aware_check_date_naive(self):
        check_date = DT.datetime(2023, 5, 3, 12, 0, 0, tzinfo=DT.timezone.utc)
        after_date = DT.datetime(2023, 5, 2, 12, 0, 0)
        assert is_checkdate_after_date(check_date, after_date) is True

    @pytest.mark.unit
    def test_date_in_range_mixed_awareness(self):
        start_date = DT.datetime(2023, 5, 1, 0, 0, 0, tzinfo=DT.timezone.utc)
        check_date = DT.datetime(2023, 5, 2, 12, 0, 0)
        end_date = DT.datetime(2023, 5, 3, 23, 59, 59, tzinfo=DT.timezone.utc)
        assert is_date_in_range(start_date, check_date, end_date) is True


class TestWeeksBetweenDates:

    @pytest.mark.unit
    def test_weeks_between_dates_mixed_awareness(self):
        date1 = DT.datetime(2023, 1, 1, 12, 0, 0, tzinfo=DT.timezone.utc)
        date2 = DT.datetime(2023, 1, 8, 11, 0, 0)
        assert weeks_between_dates(date1, date2) == 1

    @pytest.mark.unit
    def test_weeks_between_dates_string_inputs(self):
        assert weeks_between_dates("2023-01-01", "2023-01-15") == 2



@pytest.mark.unit
class TestCalculateCensusDate:
    """EVA / census date calculated as a percentage of the instructional period."""

    def test_standard_sixteen_week_term_at_ten_percent(self):
        # 116 days * 10% = 11.6 -> 12 days after the start.
        assert calculate_census_date(
            DT.date(2026, 1, 12), DT.date(2026, 5, 8), 10.0
        ) == DT.date(2026, 1, 24)

    def test_percentage_is_configurable(self):
        start, end = DT.date(2026, 1, 12), DT.date(2026, 5, 8)

        assert calculate_census_date(start, end, 25.0) == DT.date(2026, 2, 10)
        assert calculate_census_date(start, end, 50.0) == DT.date(2026, 3, 11)

    def test_single_day_term_does_not_divide_by_zero(self):
        assert calculate_census_date(
            DT.date(2026, 1, 12), DT.date(2026, 1, 12), 10.0
        ) == DT.date(2026, 1, 12)

    def test_end_before_start_returns_none(self):
        assert calculate_census_date(
            DT.date(2026, 5, 8), DT.date(2026, 1, 12), 10.0
        ) is None

    def test_zero_or_negative_percent_returns_the_start_date(self):
        start, end = DT.date(2026, 1, 12), DT.date(2026, 5, 8)

        assert calculate_census_date(start, end, 0) == start
        assert calculate_census_date(start, end, -5) == start

    def test_unparseable_input_returns_none(self):
        assert calculate_census_date("not a date", DT.date(2026, 5, 8), 10.0) is None
        assert calculate_census_date(None, DT.date(2026, 5, 8), 10.0) is None

    def test_accepts_strings_and_datetimes(self):
        expected = DT.date(2026, 1, 24)

        assert calculate_census_date("01-12-2026", "05-08-2026", 10.0) == expected
        assert calculate_census_date(
            DT.datetime(2026, 1, 12), DT.datetime(2026, 5, 8), 10.0
        ) == expected

    def test_census_date_always_falls_within_the_course(self):
        start, end = DT.date(2026, 1, 12), DT.date(2026, 5, 8)

        for percent in (1, 10, 25, 50, 100):
            census = calculate_census_date(start, end, percent)
            assert start <= census <= end


@pytest.mark.unit
class TestLooksLikeAScrapedDate:
    """The guard that keeps dateparser's permissiveness out of scraped cells."""

    @pytest.mark.parametrize(
        "text", ["N/A", "TBD", "Not Applicable", "-", "", "   ", None, "a", "b"]
    )
    def test_placeholders_are_rejected(self, text):
        from cqc_cpcc.utilities.date import looks_like_a_scraped_date

        assert looks_like_a_scraped_date(text) is False

    @pytest.mark.parametrize(
        "text", ["1/12/2026", "2026-01-12", "January 12, 2026", "1/12/2026 (Monday)"]
    )
    def test_real_dates_are_accepted(self, text):
        from cqc_cpcc.utilities.date import looks_like_a_scraped_date

        assert looks_like_a_scraped_date(text) is True

    def test_the_placeholder_dateparser_would_have_accepted(self):
        """This is the exact value that made the guard necessary."""
        from cqc_cpcc.utilities.date import get_datetime, looks_like_a_scraped_date

        assert get_datetime("N/A") is not None  # dateparser does not raise here
        assert looks_like_a_scraped_date("N/A") is False


@pytest.mark.unit
class TestPurgeRejectsPlaceholders:
    """The purge is the last line before a placeholder becomes "the latest date".

    ``get_latest_date`` feeds the attendance start date. Before the digit guard,
    a roster whose Last Attendance cells all read "N/A" purged to ``["N/A"]``,
    sorted to ``"N/A"``, and parsed into today -- so attendance was marked from a
    date nobody had recorded.
    """

    def test_the_one_placeholder_dateparser_accepts_is_purged(self):
        """"N/A" is the dangerous case: the try/except below never fires for it."""
        from cqc_cpcc.utilities.date import (
            get_datetime,
            purge_empty_and_invalid_dates,
        )

        assert get_datetime("N/A") is not None  # no ValueError to catch
        assert purge_empty_and_invalid_dates(["N/A"]) == []

    @pytest.mark.parametrize("placeholder", ["TBD", "-", "Not Applicable", "", "  "])
    def test_the_other_placeholders_are_purged_too(self, placeholder):
        from cqc_cpcc.utilities.date import purge_empty_and_invalid_dates

        assert purge_empty_and_invalid_dates([placeholder]) == []

    def test_a_digit_bearing_non_date_is_still_purged_by_the_parser(self):
        """The digit guard did not make the ValueError below it dead code."""
        from cqc_cpcc.utilities.date import purge_empty_and_invalid_dates

        assert purge_empty_and_invalid_dates(["2026-99-99"]) == []

    def test_real_dates_survive_alongside_placeholders(self):
        from cqc_cpcc.utilities.date import purge_empty_and_invalid_dates

        assert purge_empty_and_invalid_dates(
            ["N/A", "09/07/2026", "", "TBD", "09/01/2026"]
        ) == ["09/07/2026", "09/01/2026"]

    def test_a_roster_of_placeholders_yields_no_latest_date(self):
        from cqc_cpcc.utilities.date import get_latest_date

        assert get_latest_date(["N/A", "", "TBD"]) == ""

    def test_the_latest_real_date_still_wins(self):
        from cqc_cpcc.utilities.date import get_latest_date

        assert get_latest_date(
            ["09/01/2026", "N/A", "09/08/2026", "08/25/2026"]
        ) == "09/08/2026"

    def test_the_earliest_real_date_still_wins(self):
        from cqc_cpcc.utilities.date import get_earliest_date

        assert get_earliest_date(
            ["09/01/2026", "N/A", "09/08/2026", "08/25/2026"]
        ) == "08/25/2026"


@pytest.mark.unit
class TestTermForDateEdges:
    """Course filtering runs before any course page opens, so this is guessy input."""

    @pytest.mark.parametrize("value", ["N/A", "", "not a date", None, object()])
    def test_an_unusable_value_yields_no_term_rather_than_raising(self, value):
        from cqc_cpcc.utilities.date import term_for_date

        assert term_for_date(value) is None

    def test_every_calendar_month_maps_to_a_semester(self):
        """No month may fall through -- a course in one would vanish from the picker."""
        from cqc_cpcc.utilities.date import term_for_date

        assert all(term_for_date(DT.date(2026, month, 15)) for month in range(1, 13))

    def test_a_real_date_resolves_to_a_semester_and_year(self):
        from cqc_cpcc.utilities.date import _TERM_BY_START_MONTH, term_for_date

        month = sorted(_TERM_BY_START_MONTH)[0]

        assert term_for_date(DT.date(2026, month, 15)) == (
            _TERM_BY_START_MONTH[month], "2026"
        )


@pytest.mark.unit
class TestTimezoneNormalisation:
    """dateparser returns aware datetimes; the rest of the code builds naive ones.

    Comparing the two raises, so every comparison helper normalises first.
    """

    def test_a_naive_datetime_is_reported_as_not_aware(self):
        from cqc_cpcc.utilities.date import _is_timezone_aware

        assert _is_timezone_aware(DT.datetime(2026, 9, 7)) is False

    def test_none_is_reported_as_not_aware(self):
        from cqc_cpcc.utilities.date import _is_timezone_aware

        assert _is_timezone_aware(None) is False

    def test_an_aware_datetime_is_reported_as_aware(self):
        from cqc_cpcc.utilities.date import _is_timezone_aware

        aware = DT.datetime(2026, 9, 7, tzinfo=DT.timezone.utc)

        assert _is_timezone_aware(aware) is True

    def test_stripping_a_naive_datetime_leaves_it_unchanged(self):
        from cqc_cpcc.utilities.date import _strip_timezone

        naive = DT.datetime(2026, 9, 7, 13, 45)

        assert _strip_timezone(naive) == naive

    def test_stripping_an_aware_datetime_shifts_it_to_utc_then_drops_the_zone(self):
        from cqc_cpcc.utilities.date import _strip_timezone

        aware = DT.datetime(
            2026, 9, 7, 13, 45, tzinfo=DT.timezone(DT.timedelta(hours=-4))
        )

        assert _strip_timezone(aware) == DT.datetime(2026, 9, 7, 17, 45)

    def test_none_normalises_to_none(self):
        from cqc_cpcc.utilities.date import _ensure_naive_datetime

        assert _ensure_naive_datetime(None) is None
